Repository Chandler-Community/Serenity, pull requests merged in 2023-02, with the labels that each got.

#1 Test PR
  README.md
Labels: Статус: подтверждено, Статус: не пройдена проверка

#9 Fix grammatical errors
  INFO/кратко про сервер.txt
  INFO/лор.txt
  INFO/правила дискорд (пусть будут).txt
  INFO/правила публикации PR'а.txt
  INFO/ссылки.txt
Labels: Статус: подтверждено

#13 Time boost for clown and mime + bugfix
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
Labels: Статус: подтверждено

#14 Delete clown & mime
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
Labels: Статус: подтверждено

#15 Add Builder
  Resources/Prototypes/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/Roles/Jobs/Engineering/builder.yml
  Resources/Prototypes/Roles/play_time_trackers.yml
Labels: Статус: подтверждено

#17 Builder fix
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Prototypes/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  data/CentCommShuttle.yml
Labels: баг, Статус: подтверждено
